openapi: 3.1.0
info:
  title: upgrade-npm-package CLI Tool Contracts
  version: 0.1.0
  description:
    Contracts for the cmd-ts CLI tool that lists newer versions and
    performs safe upgrades with CI fallback. This defines the expected
    behavior and data structures.
servers:
  - url: http://localhost
paths:
  /deps/newer:
    get:
      summary: List newer stable versions for all direct dependencies
      description:
        Returns newer versions available on npmjs.org for dependencies,
        devDependencies, and optionalDependencies.
      responses:
        '200':
          description: Newer versions listed
          content:
            application/json:
              schema:
                type: object
                properties:
                  dependencies:
                    type: array
                    items:
                      $ref: '#/components/schemas/DependencyNewer'
        '503':
          description: Registry unavailable
  /upgrade/admin:
    post:
      summary: Run admin fast path
      description:
        Runs `pnpm run ci:admin` and accepts resulting state if passing; no
        per-version iteration.
      responses:
        '200':
          description: Admin path executed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SummaryReport'
        '422':
          description: Admin CI failed
  /upgrade/iterative:
    post:
      summary: Run iterative upgrade attempts
      description:
        Attempts upgrades from newest to oldest newer version for each
        dependency; runs `pnpm run ci` after each.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                includeOptional:
                  type: boolean
                  default: true
                allowPrerelease:
                  type: boolean
                  default: false
      responses:
        '200':
          description: Iterative process completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SummaryReport'
        '409':
          description: Peer dependency conflicts encountered (see report)
components:
  schemas:
    DependencyNewer:
      type: object
      properties:
        name:
          type: string
        section:
          type: string
          enum: [dependencies, devDependencies, optionalDependencies]
        currentVersion:
          type: string
        newer:
          type: array
          items:
            type: string
    AttemptResult:
      type: object
      properties:
        packageName:
          type: string
        candidateVersion:
          type: string
        ciStatus:
          type: string
          enum: [pass, fail]
        reason:
          type: string
          nullable: true
        action:
          type: string
          enum: [accept, revert]
        timestamp:
          type: string
          format: date-time
    SummaryReport:
      type: object
      properties:
        upgraded:
          type: array
          items:
            type: object
            properties:
              name: { type: string }
              from: { type: string }
              to: { type: string }
        skipped:
          type: array
          items:
            type: object
            properties:
              name: { type: string }
              reason: { type: string }
        remainingOutdated:
          type: array
          items:
            type: string
        warnings:
          type: array
          items:
            type: string
